### ISSUE TITLE
Bug al abrir la página

### ISSUE THREAD

**Issue by JuanmaLambre** [arpb2/frontend#16]
Me sucedió probando #15. 

Cuando abro Blockly desde la home no carga nada (la pestaña de Network aparece vacía) y en la página sólo se ve la barra azul con la palabra "Logo", el textbox donde se muestra el código traducido y un texto que dice "```<xml xmlns="https://developers.google.com/blockly/xml"><block type="text" id="+!Df2.jp}9oet`7}jqGk" x="70" y="30"><field name="TEXT"/></block></xml>```". 

Si le doy refresh a la página todo carga a la normalidad :man_shrugging: 

![](https://i.postimg.cc/FhDkSzxp/Screenshot-at-2020-01-15-10-38-32.png?dl=1)

**Comment by mastanca** [comment]
Si así estaba antes, era el XML que viene con la demo para debuggear. Ya lo saqué en el PR #15
